### ISSUE TITLE
Wrong CIGAR (insertion of length 0)

### ISSUE THREAD

**Issue by lucventurini** [ydLiu-HIT/deSALT#16]
Dear @ydLiu-HIT , I have recently tried out your deSALT after reading the publication, and I am impressed at the product. I am however encountering a bug in your most recent release (1.5.1), ie this wrong CIGAR:

```107S18M2461N0I49D12M2D28M4I3M2I22M2D5M1D4M2I20M3I5M4D21M```

The problem is the zero-length insertion, **0I**, right after the intron (2461N). This error is crashing a program of ours, [portcullis](https://github.com/maplesond/portcullis), which we would like to use to categorise the junctions found by deSALT.

For the time being I can simply filter out the offending reads, but I think that fixing this minor bug might avoid crashes in other programs as well.

Thank you again for such a product!

Kind regards

**Comment by ydLiu-HIT** [comment]
Hi, ucventurini
Thank you for using deSALT. May you share the query and reference that trigger the issue, I may have a look to solve it. Otherwise, I can just delete the zero-length insertion and merge the 49-length deletion to the intron, but this may not deal with the error from the algorithm itself.

Best,

**Comment by lucventurini** [comment]
Dear @ydLiu-HIT,
                               the alignment was against the TAIR10 version of the *Arabidopsis thaliana* genome (available [here](ftp://ftp.arabidopsis.org/home/tair/Sequences/whole_chromosomes/); I did concatenate the seven `TAIR10_*.fas` files with `cat`). 

The command line was:

```deSALT aln -T -t 10 -x ont2d -f not_guided TAIR10.fas.deS ./Arab_thal_MinION_190919/20190919_1416_Arab_thal_190919/pass.fastq.gz```

Commit: 264ab46a4fd29cc85afaf9d7acee9a1f19d4472e

I also attach here the FASTQ of the 27 reads of my batch (out of over 200k) that cause the bug.

[standard.T.wrong.zip](https://github.com/ydLiu-HIT/deSALT/files/4019227/standard.T.wrong.zip)

Many thanks for the quick reply.

Kind regards
I attach a

**Comment by ydLiu-HIT** [comment]
Thank you for sharing the query and reference, I will look into it and feedback to you as soon as possible.

Best.

**Comment by ydLiu-HIT** [comment]
Hi,
I have tested your reads but didn't found any operator like "2461N0I49D" with zero-length. I think the reason is that the reads you shared with me contain only parts of reads that come from that region, which deSALT can't generate completely exons due to the special 2-pass algorithm, so the alignment result I got may different from you. Thus, if you can share the entire dataset, maybe I will find the key point.
What's more, I have already deal with the condition with zero-length and other problematic cigar operators which have been released with version 1.5.2 (https://github.com/ydLiu-HIT/deSALT/archive/v1.5.2.zip). I think that will help you well.

Thank you again for using deSALT and help me fix errors in my program.
Best, 
yadong

**Comment by lucventurini** [comment]
Many thanks, I will try the new version in the morning!

**Comment by lucventurini** [comment]
Dear @ydLiu-HIT, the new release seems to have fixed the problem.

Many thanks!
