### ISSUE TITLE
mapped reads with zero coordinate

### ISSUE THREAD

**Issue by HegedusB** [ydLiu-HIT/deSALT#17]
Hi,
When I tried to convert the deSALT mapped, illumina corrected nanopore reads, to sorted bam file with samtools, I get this massage in many times: "[W::sam_parse1] mapped query cannot have zero coordinate; treated as unmapped". Seemingly the sorted bam file looks nice but I am curious about the meaning of this error massage.

Can you give me an advice which parameters works best for short exons. My fungi strain has lots of genes with exons sorter than 10bp. Is it possible at all to align correctly the polished nanopore reads onto these short exons. My previously used command looks like this:
deSALT aln -t 40 -I 1000 -k 21 -l 14 -s 2 -x ccs -O6,24 -M4 -o ./aln.sam ./refgen_index ../refgen.fasta
The resulting alignment is great in average but has problems with the short exons.

Thanks for any help, suggestions!

**Comment by ydLiu-HIT** [comment]
Hi，
Sorry for replying to you so later.
I saw you use the command with option '-k 21', which is the kmer size for creating RdBG-index. When you use '-k 21' option to align reads to genome, you must create index with 'deSALT index -k 21', because the default kmer size is 22bp.

If you are sure you have created index with '-k 21' and  your fungi strain has lots of genes with exons sorter than 10bp, '-a 6' is recommended when you align reads to genome.
If the problem still exists, you can share me your reference genome and some reads which have zero-coordinate or have exons short than 10bp, I will debug in my side and solve the problem.

Best.

**Comment by HegedusB** [comment]
Hi,
Thanks for your help. In the coming days I will try out your suggestions for sure! I have tried already to change the index -k 22 to -k 21 but I have run into troubles. Without any parameters the indexing works fine but when I want to specify the -k value than the indexing seemingly runs well but do not produce any output files.
 I am using the deSALT v1.5.2 from bioconda.

**Comment by ydLiu-HIT** [comment]
If you have troubles when creating index using '-k 21', you can directly use '-k 22'(default), and align reads to genome with 'deSALT aln -k 22', the results have no significant difference between '-k21' and '-k22' I think.

**Comment by HegedusB** [comment]
I tried out with -k 22 (indexing, alignment) and there was truly no significant difference. If you do not mind I will send you some reads which were not correctly aligned because they have really short exons. Can I use you email found on your profile page (ydliu@hit.edu.cn)?

**Comment by ydLiu-HIT** [comment]
Of course.
But I can't reply to you quickly because the 2019 new coronavirus spread widely in China. I must stay at home and can't back to school. Thus, I have no enough computer memory to run deSALT.
But, if your reference genome is small, and few reads, I can try to test on my PC.

Best.
