### ISSUE TITLE
mapping of partial reads

### ISSUE THREAD

**Issue by michieitel** [ydLiu-HIT/deSALT#5]
Hi!

I mapped ONT cDNA reads with deSALT using these options
`deSALT aln -t 20 -K 21 -k 14 -s 2 -x ont1d `

While it performed well for many exons it often maps parts of reads with most of the reads marked as soft clipped (see attached screenshot of the comparison to GMAP; for deSALT one can see many small and unlinked bits of reads).

Can you please help me to improve my settings to prevent these cases?

Thank you very much.

Kind regards,
Michael

![deSALT_vs_GMAP](https://user-images.githubusercontent.com/12069446/61521164-f00b1400-aa0f-11e9-9d52-7b1548f46224.png)

**Comment by michieitel** [comment]
Hi!
Any suggestions to my question?
Thanks
Michael

**Comment by ydLiu-HIT** [comment]
Hi, Michael,

I am very sorry to reply you so later due to my personal reasons.
Thank you for using deSALT and your report first. When I test deSALT with my reads showed in papers, I couldn't find the issues like the screenshot. So if you can share me some of the reads you have used, I can test my program in your reads and give you some suggestions.

Looking forward to your reply.
